[package]
name = "lycan"
description = "A simple World of Warcraft addon manager."
version = "0.1.0"
license = "GPLv3+"
kind = "Binary"
backend = "C"
binaries = ["lycan"]

[toolchain]
version = "2.2.6"

[dependencies]
zippy = ">= 0.10.6"
